-- Sync active order statuses with the development canonical state.
-- Existing rows are matched by status_key so order/status history references keep
-- their environment-specific UUIDs. Transition links are resolved by status_key.

DROP TABLE IF EXISTS pg_temp.desired_order_statuses;

CREATE TEMP TABLE desired_order_statuses (
  id uuid NOT NULL,
  display_order integer NOT NULL,
  status_key text NOT NULL,
  patient_status_label text,
  patient_microcopy text,
  patient_action_required boolean NOT NULL,
  admin_status_label text NOT NULL,
  admin_microcopy text,
  next_step_owner text NOT NULL,
  expiration_timer_hours integer,
  is_terminal boolean NOT NULL,
  is_active boolean NOT NULL,
  is_patient_visible boolean NOT NULL,
  next_status_key text,
  failure_status_key text
) ON COMMIT DROP;

INSERT INTO desired_order_statuses (
  id,
  display_order,
  status_key,
  patient_status_label,
  patient_microcopy,
  patient_action_required,
  admin_status_label,
  admin_microcopy,
  next_step_owner,
  expiration_timer_hours,
  is_terminal,
  is_active,
  is_patient_visible,
  next_status_key,
  failure_status_key
)
VALUES
  (
    '6be90bf1-532a-4ceb-8651-b5f47748ded8',
    1,
    'order_created',
    'Order Started',
    $$We've created your order and are getting things ready.$$,
    false,
    'Order Created',
    'Order record created in the system.',
    'system',
    NULL,
    false,
    true,
    true,
    'shipping_details_required',
    NULL
  ),
  (
    '2dc13882-42c4-47b5-b2c6-c51f005c85f6',
    2,
    'shipping_details_required',
    'Add Shipping Details',
    'Please add your shipping address so we can continue processing your order.',
    true,
    'Shipping Details Required',
    'Shipping information is missing or incomplete.',
    'system',
    NULL,
    false,
    true,
    true,
    'provider_order_creation_pending',
    NULL
  ),
  (
    '98e17224-c4c2-4a5e-a3a1-435aaf8c58c8',
    3,
    'provider_order_creation_pending',
    'Order Being Created In Provider',
    'We are creating your order in your medical platform.',
    false,
    'Order Pending Creation On Provider',
    'Order pending creation on provider platform',
    'patient',
    NULL,
    false,
    true,
    false,
    'patient_questionnaire_pending',
    'provider_order_creation_error'
  ),
  (
    '4877d87a-89d8-489b-89a6-14301d270328',
    4,
    'patient_questionnaire_pending',
    'Complete Patient Questionnaire',
    'Please complete the required questionnaire so we can continue processing your order.',
    true,
    'Patient Questionnaire Pending',
    'Required patient questionnaire has not been completed by the patient.',
    'patient',
    NULL,
    false,
    true,
    true,
    'medical_questionnaire_pending',
    NULL
  ),
  (
    '998e9cd9-4d67-4545-aeef-0b60d7d24dc7',
    5,
    'medical_questionnaire_pending',
    'Complete Medical Questions',
    'Answer a few medical questions so a licensed provider can safely review your treatment.',
    true,
    'Medical Questionnaire Pending',
    'Required medical questionnaire has not been completed by the patient.',
    'patient',
    NULL,
    false,
    true,
    true,
    'provider_review_pending',
    NULL
  ),
  (
    'ab275bc0-3705-4cfd-9223-66bd394049c7',
    6,
    'provider_review_pending',
    'Under Medical Review',
    'A licensed provider is reviewing your information to make sure this treatment is right for you.',
    false,
    'Provider Review Pending',
    'Order is awaiting review by a licensed provider.',
    'provider',
    NULL,
    false,
    true,
    true,
    'provider_approved',
    'provider_rejected'
  ),
  (
    'c093029c-e113-47fe-8a19-94c65f98b817',
    7,
    'provider_approved',
    'Treatment Approved',
    'Your treatment has been approved by a licensed provider.',
    false,
    'Provider Approved',
    'Treatment approved by provider and cleared to proceed.',
    'system',
    NULL,
    false,
    true,
    true,
    'payment_pending',
    NULL
  ),
  (
    '4477ac0d-33d9-4005-8847-2681ce1171b6',
    8,
    'payment_pending',
    'Payment Pending',
    'Your payment will be processed by the Payment Provider',
    false,
    'Payment Pending',
    'Pending payment processing on Payment Provider',
    'payment_provider',
    NULL,
    false,
    true,
    true,
    'payment_collected',
    'payment_failed'
  ),
  (
    '39820324-6ee6-4a00-b673-9b0bcbfd37f6',
    9,
    'payment_collected',
    'Payment Collected',
    'Your payment has been collected.',
    false,
    'Payment Collected',
    'Payment successful on Payment provider',
    'system',
    NULL,
    false,
    true,
    true,
    'order_approved',
    NULL
  ),
  (
    'a062fdd5-09cf-452f-8314-8359e12ee4b6',
    10,
    'order_approved',
    'Order Approved',
    'Your order has been approved and is ready for the next step.',
    false,
    'Order Approved',
    'Payment and initial order checks are complete, and the order is approved to continue.',
    'system',
    NULL,
    false,
    true,
    true,
    'order_sent_to_pharmacy',
    'order_on_hold'
  ),
  (
    'c426721b-b4a9-4f43-a248-bfbb7249aff1',
    11,
    'order_sent_to_pharmacy',
    NULL,
    NULL,
    false,
    'Order Sent To Pharmacy',
    'Order has been sent to the pharmacy and is awaiting pharmacy review.',
    'pharmacy',
    NULL,
    false,
    true,
    false,
    'pharmacy_approval_pending',
    NULL
  ),
  (
    'c01adfc1-e622-4661-86cb-7b636d5ce1cb',
    12,
    'pharmacy_approval_pending',
    'Pending Pharmacy Approval',
    'The pharmacy is reviewing your prescription to ensure it meets all safety and regulatory requirements.',
    false,
    'Pharmacy Approval Pending',
    'Order is pending pharmacy review and approval.',
    'pharmacy',
    NULL,
    false,
    true,
    true,
    'pharmacy_approved',
    'pharmacy_rejected'
  ),
  (
    '4d578f4c-f6c5-4996-878e-dd6674b7bb48',
    13,
    'pharmacy_approved',
    'Approved By Pharmacy',
    'The pharmacy has approved your order and is preparing it for fulfillment.',
    false,
    'Pharmacy Approved',
    'Pharmacy has approved the prescription for fulfillment.',
    'pharmacy',
    NULL,
    false,
    true,
    true,
    'fulfillment_in_progress',
    NULL
  ),
  (
    '3d3dfaae-99af-4ff1-8171-8b5f28f94d7a',
    14,
    'fulfillment_in_progress',
    'Being Prepared',
    'Your treatment is being prepared and packaged by the pharmacy.',
    false,
    'Fulfillment In Progress',
    'Pharmacy is preparing and packaging the order.',
    'pharmacy',
    NULL,
    false,
    true,
    true,
    'final_pharmacy_verification',
    NULL
  ),
  (
    'bee55703-1fb8-46a5-b952-e096711b8df2',
    15,
    'final_pharmacy_verification',
    'Final Quality Check',
    'The pharmacy is completing a final safety and quality check before shipment.',
    false,
    'Final Pharmacy Verification',
    'Final compliance and safety verification in progress prior to shipment.',
    'pharmacy',
    NULL,
    false,
    true,
    true,
    'in_transit',
    NULL
  ),
  (
    '898f90a5-22a4-439a-9865-90124ba9ac06',
    16,
    'in_transit',
    'Order Shipped!',
    'Your order has shipped and is on its way to you. Tracking details will be available soon.',
    false,
    'In Transit',
    'Shipment has been handed off to the carrier.',
    'carrier',
    NULL,
    false,
    true,
    true,
    'delivered',
    'shipping_exception'
  ),
  (
    '33bee4fd-cb66-4b37-a22b-d69fd0cb6734',
    17,
    'delivered',
    'Delivered',
    $$Your order has been delivered. You're all set!$$,
    false,
    'Delivered',
    'Shipment confirmed as delivered to the patient.',
    'carrier',
    NULL,
    true,
    true,
    true,
    'id_verification_failed',
    NULL
  ),
  (
    'c2ae782b-c473-4b1d-af1e-58f2996e06be',
    18,
    'id_verification_failed',
    'Identity Verification Needed',
    $$We couldn't verify your identity. Please try again to continue your order.$$,
    true,
    'ID Verification Failed',
    'Identity verification attempt failed or expired.',
    'patient',
    NULL,
    false,
    true,
    true,
    'medical_questionnaire_incomplete',
    NULL
  ),
  (
    '6fcd212a-5965-4657-86b5-5a78c9386322',
    19,
    'medical_questionnaire_incomplete',
    'Medical Questions Incomplete',
    'Some required medical questions are missing. Please complete them to continue.',
    true,
    'Medical Questionnaire Incomplete',
    'Questionnaire submission is incomplete or invalid.',
    'patient',
    NULL,
    false,
    true,
    true,
    'medical_followup_required',
    NULL
  ),
  (
    '42091fa0-7284-41d9-9de4-5004126c3cf3',
    20,
    'medical_followup_required',
    'Provider Needs More Information',
    'Your provider needs a bit more information before approving your treatment.',
    true,
    'Provider Follow-Up Required',
    'Provider requested additional patient input.',
    'patient',
    NULL,
    false,
    true,
    true,
    'payment_failed',
    NULL
  ),
  (
    '8479a8ab-e84e-4d95-aeb5-eee25b80b181',
    21,
    'payment_failed',
    'Payment Issue',
    'There was an issue processing your payment. Please update your payment method to continue.',
    true,
    'Payment Failed',
    'Payment attempt failed or was declined.',
    'patient',
    NULL,
    false,
    true,
    true,
    'provider_rejected',
    NULL
  ),
  (
    '7a79f6ba-afa5-4a45-89ee-fcce868fd0ca',
    22,
    'provider_rejected',
    'Treatment Not Approved',
    $$Thank you for submitting your intake form. After review, the healthcare provider determined this treatment plan is not clinically appropriate at this time.

If you believe this was made in error, please contact support within 48 hours so we can escalate your case.

If we don’t hear from you, your order will be cancelled. If the prescription isn’t approved, you’ll receive a full refund. Please let us know how you’d like to proceed.$$,
    false,
    'Provider Rejected',
    'Provider did not approve treatment.',
    'provider',
    0,
    true,
    true,
    true,
    'pharmacy_rejected',
    NULL
  ),
  (
    'dd1fc887-1726-4f82-be33-ea0b27f69c52',
    23,
    'pharmacy_rejected',
    'Issue With Pharmacy Approval',
    $$The pharmacy couldn't approve this order. Our team is reviewing next steps.$$,
    false,
    'Pharmacy Rejected',
    'Pharmacy rejected prescription or fulfillment request.',
    'ops',
    NULL,
    false,
    true,
    true,
    'order_on_hold',
    NULL
  ),
  (
    '56ad567c-d070-4ff6-8cfa-dcce359273fa',
    24,
    'order_on_hold',
    'Order Temporarily On Hold',
    'Your order is temporarily on hold while we resolve an internal issue.',
    false,
    'Order On Hold',
    'Order paused due to operational or compliance issue.',
    'ops',
    NULL,
    false,
    true,
    true,
    'inventory_unavailable',
    NULL
  ),
  (
    'a8b0b0b2-c39f-49ac-a288-74fd1768b4df',
    25,
    'inventory_unavailable',
    'Item Temporarily Unavailable',
    $$One or more items in your order are temporarily unavailable. We're working on a solution.$$,
    false,
    'Inventory Unavailable',
    'Required inventory not available for fulfillment.',
    'pharmacy',
    NULL,
    false,
    true,
    true,
    'shipping_exception',
    NULL
  ),
  (
    '9add1741-1f89-4ca0-9a0a-3d7784ec61f4',
    26,
    'shipping_exception',
    'Shipping Delay',
    $$There's a delay with your shipment. We're monitoring the situation closely.$$,
    false,
    'Shipping Exception',
    'Carrier reported an exception or delivery issue.',
    'ops',
    NULL,
    false,
    true,
    true,
    'order_cancelled',
    NULL
  ),
  (
    '6e35c2af-cc8d-47e2-8be0-6f1bac238a08',
    27,
    'order_cancelled',
    'Order Cancelled',
    'This order has been cancelled. If you have questions, our support team can help.',
    false,
    'Order Cancelled',
    'Order cancelled by patient, admin, or system.',
    'ops',
    0,
    true,
    true,
    true,
    NULL,
    NULL
  ),
  (
    '6f38adcf-3a80-4770-bf72-5492970479e9',
    28,
    'order_pending_cancellation',
    'Order Pending Cancellation',
    'Your order is pending processing for cancellation and refund eligibility calculation.',
    false,
    'Order Pending Cancellation',
    'Order is Pending Cancellation',
    'system',
    NULL,
    false,
    true,
    true,
    'order_cancellation_processing',
    NULL
  ),
  (
    '32b663c8-21de-4654-a6ff-93828db2454d',
    29,
    'order_cancellation_processing',
    'Order Cancellation Processing',
    'Your order cancellation is being processed.',
    false,
    'Order Cancellation Processing',
    'Order cancellation is being processed',
    'system',
    NULL,
    false,
    true,
    true,
    'order_cancelled',
    'order_cancellation_error'
  ),
  (
    '0f48b184-1e22-49f4-8c32-a9bc3d7362b5',
    30,
    'provider_order_creation_error',
    NULL,
    NULL,
    false,
    'Provider Order Creation Error',
    'Error creating order on Provider Platform',
    'system',
    0,
    false,
    true,
    false,
    'order_cancelled',
    NULL
  ),
  (
    '19f69fd5-574d-447b-b4dd-b4a3d85d2827',
    31,
    'order_cancellation_error',
    'Cancellation Issue',
    'We hit an issue while cancelling your order. Our support team will review it.',
    false,
    'Order Cancellation Error',
    'Order cancellation processing failed and requires operational follow-up.',
    'ops',
    0,
    true,
    true,
    true,
    NULL,
    NULL
  ),
  (
    'e1d2c3b4-a5f6-4789-8123-456789abcdef',
    32,
    'order_expired',
    'Order Expired',
    'This order expired before it could be completed. You can start again anytime.',
    false,
    'Order Expired',
    'Order expired due to patient inactivity beyond the configured threshold.',
    'system',
    0,
    true,
    true,
    true,
    NULL,
    NULL
  );

INSERT INTO public.order_statuses (
  id,
  display_order,
  status_key,
  patient_status_label,
  patient_microcopy,
  patient_action_required,
  admin_status_label,
  admin_microcopy,
  next_step_owner,
  expiration_timer_hours,
  is_terminal,
  is_active,
  is_patient_visible,
  next_status_id,
  failure_status_id
)
SELECT
  id,
  display_order,
  status_key,
  patient_status_label,
  patient_microcopy,
  patient_action_required,
  admin_status_label,
  admin_microcopy,
  next_step_owner,
  expiration_timer_hours,
  is_terminal,
  is_active,
  is_patient_visible,
  NULL::uuid,
  NULL::uuid
FROM desired_order_statuses
ON CONFLICT (status_key) DO UPDATE
SET
  display_order = EXCLUDED.display_order,
  patient_status_label = EXCLUDED.patient_status_label,
  patient_microcopy = EXCLUDED.patient_microcopy,
  patient_action_required = EXCLUDED.patient_action_required,
  admin_status_label = EXCLUDED.admin_status_label,
  admin_microcopy = EXCLUDED.admin_microcopy,
  next_step_owner = EXCLUDED.next_step_owner,
  expiration_timer_hours = EXCLUDED.expiration_timer_hours,
  is_terminal = EXCLUDED.is_terminal,
  is_active = EXCLUDED.is_active,
  is_patient_visible = EXCLUDED.is_patient_visible;

UPDATE public.order_statuses AS target
SET
  is_active = false,
  next_status_id = NULL,
  failure_status_id = NULL
WHERE target.is_active = true
  AND NOT EXISTS (
    SELECT 1
    FROM desired_order_statuses AS desired
    WHERE desired.status_key = target.status_key
  );

UPDATE public.order_statuses AS target
SET
  next_status_id = next_status.id,
  failure_status_id = failure_status.id
FROM desired_order_statuses AS desired
LEFT JOIN public.order_statuses AS next_status
  ON next_status.status_key = desired.next_status_key
LEFT JOIN public.order_statuses AS failure_status
  ON failure_status.status_key = desired.failure_status_key
WHERE target.status_key = desired.status_key;
