-- Backend-managed passkey/WebAuthn storage for Patient UI.
--
-- Tenant RP configuration is intentionally stored server-side. Patient clients
-- choose a tenant by slug/header, but never provide rp_id, rp_name, or allowed
-- origins for verification.

CREATE TABLE IF NOT EXISTS public.tenant_passkey_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL
    REFERENCES public.tenants(id) ON DELETE CASCADE UNIQUE,
  rp_id TEXT NOT NULL,
  rp_name TEXT NOT NULL,
  allowed_origins TEXT[] NOT NULL DEFAULT '{}',
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT tenant_passkey_configs_rp_id_not_url
    CHECK (rp_id = lower(trim(rp_id)) AND rp_id !~* '^https?://'),
  CONSTRAINT tenant_passkey_configs_allowed_origins_present
    CHECK (array_length(allowed_origins, 1) IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS tenant_passkey_configs_tenant_id_idx
  ON public.tenant_passkey_configs (tenant_id);

CREATE TABLE IF NOT EXISTS public.patient_passkeys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL
    REFERENCES public.tenants(id) ON DELETE CASCADE,
  patient_id UUID NOT NULL
    REFERENCES public.patients(id) ON DELETE CASCADE,
  credential_id TEXT NOT NULL,
  credential_public_key TEXT NOT NULL,
  webauthn_user_id TEXT,
  counter BIGINT NOT NULL DEFAULT 0,
  transports TEXT[] NOT NULL DEFAULT '{}',
  device_type TEXT,
  backed_up BOOLEAN NOT NULL DEFAULT false,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT patient_passkeys_counter_nonnegative CHECK (counter >= 0),
  CONSTRAINT patient_passkeys_device_type_known
    CHECK (
      device_type IS NULL
      OR device_type IN ('singleDevice', 'multiDevice')
    )
);

-- Credential IDs are generated by authenticators for the configured RP. Treat
-- them as globally unique so a credential cannot be linked to multiple tenants
-- or patients.
CREATE UNIQUE INDEX IF NOT EXISTS patient_passkeys_credential_id_key
  ON public.patient_passkeys (credential_id);

CREATE INDEX IF NOT EXISTS patient_passkeys_patient_idx
  ON public.patient_passkeys (tenant_id, patient_id);

CREATE INDEX IF NOT EXISTS patient_passkeys_tenant_idx
  ON public.patient_passkeys (tenant_id);

CREATE TABLE IF NOT EXISTS public.patient_passkey_challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL
    REFERENCES public.tenants(id) ON DELETE CASCADE,
  patient_id UUID
    REFERENCES public.patients(id) ON DELETE CASCADE,
  ceremony_type TEXT NOT NULL,
  challenge TEXT NOT NULL UNIQUE,
  origin TEXT NOT NULL,
  rp_id TEXT NOT NULL,
  webauthn_user_id TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT patient_passkey_challenges_type_known
    CHECK (ceremony_type IN ('registration', 'authentication'))
);

CREATE INDEX IF NOT EXISTS patient_passkey_challenges_active_lookup_idx
  ON public.patient_passkey_challenges (
    tenant_id,
    ceremony_type,
    challenge,
    expires_at
  )
  WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS patient_passkey_challenges_patient_idx
  ON public.patient_passkey_challenges (tenant_id, patient_id, created_at);

ALTER TABLE public.tenant_passkey_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_passkeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_passkey_challenges ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tenant_passkey_configs'
      AND policyname = 'service_role_full_access_tenant_passkey_configs'
  ) THEN
    CREATE POLICY "service_role_full_access_tenant_passkey_configs"
      ON public.tenant_passkey_configs
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'patient_passkeys'
      AND policyname = 'service_role_full_access_patient_passkeys'
  ) THEN
    CREATE POLICY "service_role_full_access_patient_passkeys"
      ON public.patient_passkeys
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'patient_passkey_challenges'
      AND policyname = 'service_role_full_access_patient_passkey_challenges'
  ) THEN
    CREATE POLICY "service_role_full_access_patient_passkey_challenges"
      ON public.patient_passkey_challenges
      FOR ALL
      TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'update_tenant_passkey_configs_updated_at'
      AND tgrelid = 'public.tenant_passkey_configs'::regclass
  ) THEN
    CREATE TRIGGER update_tenant_passkey_configs_updated_at
      BEFORE UPDATE ON public.tenant_passkey_configs
      FOR EACH ROW
      EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'update_patient_passkeys_updated_at'
      AND tgrelid = 'public.patient_passkeys'::regclass
  ) THEN
    CREATE TRIGGER update_patient_passkeys_updated_at
      BEFORE UPDATE ON public.patient_passkeys
      FOR EACH ROW
      EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'update_patient_passkey_challenges_updated_at'
      AND tgrelid = 'public.patient_passkey_challenges'::regclass
  ) THEN
    CREATE TRIGGER update_patient_passkey_challenges_updated_at
      BEFORE UPDATE ON public.patient_passkey_challenges
      FOR EACH ROW
      EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
END $$;
