-- Product "What's Included" bullets → products.included_features
-- Environment: staging
--
-- Generated by scripts/generate-product-included-features-sql.mjs. Do not hand-edit: regenerate.
-- Source: brellohealth.com product pages ("What's Included")
--         + products.config.ts (the website-slug → platform-uuid map, per env)
--
-- WHAT THIS WRITES
--   included_features only — the bullet list the patient product page shows near the
--   CTA. A JSONB array of strings (the column is JSONB, default '[]'). The patient UI
--   hides the "What's Included" block when this array is empty, so populating it is
--   what makes the section appear. Also editable in Nexus (the "What's Included" tab).
--
-- WHAT IT DOES NOT WRITE
--   Nothing else — no price, no metadata.pdp content, no other column.
--
-- SAFE TO RE-RUN
--   Idempotent. The UPDATE's "IS DISTINCT FROM" guard means a row already holding the
--   intended array is skipped, so updated_at moves only on a real change.
--
-- SAFE AGAINST THE WRONG ROW
--   Matched on the product uuid AND the Brello tenant (resolved by slug, since the
--   tenant uuid differs per environment), so a stale uuid updates nothing rather than
--   another tenant's row. Every environment's products table also holds other tenants'
--   rows (production carries CareLink-owned compounded-* products); the tenant
--   predicate keeps this Brello-only.
--
-- 4 products in staging.

BEGIN;

-- compounded-tirzepatide — Compounded Tirzepatide  (7 bullets)
UPDATE public.products p
   SET included_features = '["Tirzepatide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '25c28469-5755-4ec0-973c-c27ba423c4e2'::uuid
   AND p.included_features IS DISTINCT FROM '["Tirzepatide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-semaglutide — Compounded Semaglutide  (7 bullets)
UPDATE public.products p
   SET included_features = '["Semaglutide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = 'e6e9d7a5-1123-4a30-b251-5f60c422201c'::uuid
   AND p.included_features IS DISTINCT FROM '["Semaglutide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-nad — Compounded NAD+  (7 bullets)
UPDATE public.products p
   SET included_features = '["NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = 'c89feb57-ba73-4123-b719-12a9e93254dc'::uuid
   AND p.included_features IS DISTINCT FROM '["NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- glp-1-and-nad-semaglutide — Empowered+ Longevity Lifestyle Plan (Semaglutide)  (8 bullets)
UPDATE public.products p
   SET included_features = '["Semaglutide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '6d84817f-7f3b-4e78-932e-8a414bb344a9'::uuid
   AND p.included_features IS DISTINCT FROM '["Semaglutide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- Check this BEFORE you COMMIT.
--
--   has_features   should be true for the products listed above.
--   n              the number of bullets on each — the medication line(s) plus the
--                  six shared service bullets.
--   first          a spot-check that the medication line landed (not an empty array).
SELECT p.name,
       jsonb_typeof(p.included_features) = 'array'
         AND jsonb_array_length(p.included_features) > 0                AS has_features,
       jsonb_array_length(COALESCE(p.included_features, '[]'::jsonb))   AS n,
       p.included_features ->> 0                                        AS first
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
 ORDER BY p.name;

-- Happy? COMMIT. Not happy? ROLLBACK — nothing above has been persisted yet.
COMMIT;
