-- Product compare-at (strike-through) prices → products.compare_at_price_cents
-- Environment: production
--
-- Generated by scripts/generate-product-pricing-sql.mjs. Do not hand-edit: regenerate.
-- Source: brellohealth.com WooCommerce product pages (display_regular_price)
--         + products.config.ts (the website-slug → platform-uuid map, per env)
--
-- WHAT THIS WRITES
--   compare_at_price_cents only — the struck-through anchor the website shows beside
--   the price ("~~$749~~ $499  Save 33%"). Configured in Nexus as "Compare-at price".
--   The saving % is derived from the two prices on the website; it is not stored.
--
-- WHAT IT DOES NOT WRITE
--   price_cents. The platform is the source of truth for what a customer is charged,
--   its values already match the live site, and writing a marketing price back is the
--   drift that once advertised a saving that did not exist. Nothing here touches it.
--
-- SAFE TO RE-RUN
--   Idempotent — re-running sets the same value, and updated_at moves only on a real
--   change. Each anchor is a genuine one (WooCommerce regular price strictly above the
--   sale price); products with no real discount (compounded-nad) are not listed.
--
-- SAFE AGAINST THE WRONG ROW / A MOVED PRICE
--   Matched on the product uuid AND the Brello tenant (resolved by slug, since the
--   tenant uuid differs per environment), so a stale uuid updates nothing rather than
--   another tenant's row. The extra "AND p.price_cents < <anchor>" means a row is set
--   only when the anchor is strictly above the current charged price — if a price has
--   moved, that row is skipped rather than made to show a false or negative saving.
--   This mirrors the app's own rule (compare-at must be higher than the price).
--
-- 11 products in production.

BEGIN;

-- compounded-tirzepatide — Compounded Tirzepatide  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = 'fedb5a5a-802d-4ca2-ac35-34d663721524'::uuid
   AND p.price_cents < 74900;

-- compounded-tirzepatide — Compounded Tirzepatide (duplicate row)  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '95737fde-85a1-48b0-871d-f14a6d3bb400'::uuid
   AND p.price_cents < 74900;

-- compounded-semaglutide — Compounded Semaglutide  (compare-at $599)
UPDATE public.products p
   SET compare_at_price_cents = 59900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '50e94723-5385-432c-bfcb-1b27fbab31d2'::uuid
   AND p.price_cents < 59900;

-- compounded-semaglutide — Compounded Semaglutide (duplicate row)  (compare-at $599)
UPDATE public.products p
   SET compare_at_price_cents = 59900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '3435f2fd-4d09-4704-a52e-c722775f8445'::uuid
   AND p.price_cents < 59900;

-- compounded-sermorelin — Compounded Sermorelin  (compare-at $599)
UPDATE public.products p
   SET compare_at_price_cents = 59900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '971f89bb-4916-479b-8b0e-a74821ccff8b'::uuid
   AND p.price_cents < 59900;

-- compounded-micc — Compounded MICC  (compare-at $386)
UPDATE public.products p
   SET compare_at_price_cents = 38600,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '34fa5ae7-c32d-435d-9dfb-182994fc3e7b'::uuid
   AND p.price_cents < 38600;

-- glp-1-and-nad-tirzepatide — Empowered+ Longevity Lifestyle Plan (Tirzepatide)  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '32ca74d1-e6e1-4371-bf80-aaa36601732c'::uuid
   AND p.price_cents < 74900;

-- glp-1-and-nad-semaglutide — Empowered+ Longevity Lifestyle Plan (Semaglutide)  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '1fc79cc3-f5bf-480c-8ade-78a323d1d090'::uuid
   AND p.price_cents < 74900;

-- glp-1-sermorelin-and-nad-tirzepatide — Thrive Forward Longevity Lifestyle Plan (Tirzepatide)  (compare-at $1099)
UPDATE public.products p
   SET compare_at_price_cents = 109900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '5e45b3f1-c637-45b3-af8f-f2f812f6fb26'::uuid
   AND p.price_cents < 109900;

-- glp-1-sermorelin-and-nad-semaglutide — Thrive Forward Longevity Lifestyle Plan (Semaglutide)  (compare-at $997)
UPDATE public.products p
   SET compare_at_price_cents = 99700,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '2d69f860-beaa-4694-883e-b07fe181fdb3'::uuid
   AND p.price_cents < 99700;

-- sermorelin-and-nad — Midlife Thrive (Sermorelin & NAD+)  (compare-at $819)
UPDATE public.products p
   SET compare_at_price_cents = 81900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '7164aee0-857e-4494-9fad-2686a0c008d8'::uuid
   AND p.price_cents < 81900;

-- Check this BEFORE you COMMIT.
--
--   Every row below should show compare_at ABOVE price, with a sensible saving.
--   A product you expected but do not see here was skipped by the price guard —
--   its charged price is no longer below the intended anchor. Investigate before
--   forcing it.
SELECT p.name,
       p.price_cents / 100.0                                        AS price,
       p.compare_at_price_cents / 100.0                             AS compare_at,
       CASE WHEN p.compare_at_price_cents > p.price_cents
            THEN round(100.0 * (p.compare_at_price_cents - p.price_cents)
                       / p.compare_at_price_cents)
       END                                                          AS saving_pct
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
   AND p.compare_at_price_cents IS NOT NULL
 ORDER BY p.name;

-- Happy? COMMIT. Not happy? ROLLBACK — nothing above has been persisted yet.
COMMIT;
