-- Product compare-at (strike-through) prices → products.compare_at_price_cents
-- Environment: development
--
-- Generated by scripts/generate-product-pricing-sql.mjs. Do not hand-edit: regenerate.
-- Source: brellohealth.com WooCommerce product pages (display_regular_price)
--         + products.config.ts (the website-slug → platform-uuid map, per env)
--
-- WHAT THIS WRITES
--   compare_at_price_cents only — the struck-through anchor the website shows beside
--   the price ("~~$749~~ $499  Save 33%"). Configured in Nexus as "Compare-at price".
--   The saving % is derived from the two prices on the website; it is not stored.
--
-- WHAT IT DOES NOT WRITE
--   price_cents. The platform is the source of truth for what a customer is charged,
--   its values already match the live site, and writing a marketing price back is the
--   drift that once advertised a saving that did not exist. Nothing here touches it.
--
-- SAFE TO RE-RUN
--   Idempotent — re-running sets the same value, and updated_at moves only on a real
--   change. Each anchor is a genuine one (WooCommerce regular price strictly above the
--   sale price); products with no real discount (compounded-nad) are not listed.
--
-- SAFE AGAINST THE WRONG ROW / A MOVED PRICE
--   Matched on the product uuid AND the Brello tenant (resolved by slug, since the
--   tenant uuid differs per environment), so a stale uuid updates nothing rather than
--   another tenant's row. The extra "AND p.price_cents < <anchor>" means a row is set
--   only when the anchor is strictly above the current charged price — if a price has
--   moved, that row is skipped rather than made to show a false or negative saving.
--   This mirrors the app's own rule (compare-at must be higher than the price).
--
-- 4 products in development.

BEGIN;

-- compounded-tirzepatide — Compounded Tirzepatide  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '29a10b97-27d9-4847-935e-488b21c8d21a'::uuid
   AND p.price_cents < 74900;

-- compounded-tirzepatide — Compounded Tirzepatide (duplicate row)  (compare-at $749)
UPDATE public.products p
   SET compare_at_price_cents = 74900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '8ce07cee-7e98-4768-bbb0-0918b00b0da9'::uuid
   AND p.price_cents < 74900;

-- compounded-semaglutide — Compounded Semaglutide  (compare-at $599)
UPDATE public.products p
   SET compare_at_price_cents = 59900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = 'fb802241-1340-405e-b272-1aa46ffd4007'::uuid
   AND p.price_cents < 59900;

-- compounded-semaglutide — Compounded Semaglutide (duplicate row)  (compare-at $599)
UPDATE public.products p
   SET compare_at_price_cents = 59900,
       updated_at             = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '9edac9a0-e2f4-4de1-a5e9-d29c0921906e'::uuid
   AND p.price_cents < 59900;

-- Check this BEFORE you COMMIT.
--
--   Every row below should show compare_at ABOVE price, with a sensible saving.
--   A product you expected but do not see here was skipped by the price guard —
--   its charged price is no longer below the intended anchor. Investigate before
--   forcing it.
SELECT p.name,
       p.price_cents / 100.0                                        AS price,
       p.compare_at_price_cents / 100.0                             AS compare_at,
       CASE WHEN p.compare_at_price_cents > p.price_cents
            THEN round(100.0 * (p.compare_at_price_cents - p.price_cents)
                       / p.compare_at_price_cents)
       END                                                          AS saving_pct
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
   AND p.compare_at_price_cents IS NOT NULL
 ORDER BY p.name;

-- Happy? COMMIT. Not happy? ROLLBACK — nothing above has been persisted yet.
COMMIT;
