-- Retire duplicate product rows → products.is_enabled = false
-- Environment: development
--
-- Generated by scripts/generate-product-duplicate-disable-sql.mjs. Do not hand-edit: regenerate.
-- Source: product-uuid-aliases.json (the known duplicate rows per env)
--         + products.config.ts (the website-slug → platform-uuid map, per env)
--
-- WHAT THIS DOES
--   Sets is_enabled = false on the known DUPLICATE product rows — a second enabled
--   row that is the same product (same sku + price) as the canonical one the config
--   points at, and which otherwise renders a second card / an empty product page.
--   The patient-api product queries filter on is_enabled = true, so a disabled row
--   drops out of the storefront immediately.
--
-- WHY DISABLE, NOT DELETE
--   A product row is referenced by orders, subscriptions, faqs, medications,
--   categories and terms acceptances. A DELETE would fail on those foreign keys or
--   orphan a real customer order. Disabling is safe (existing orders keep working;
--   it only hides the row from NEW purchases) and is trivially reversible — set
--   is_enabled back to true. A DELETE, if ever wanted, is a separate deliberate step
--   taken only after confirming zero dependents (see the diagnostic below).
--
-- LOOK BEFORE YOU LEAP
--   The diagnostic SELECT below shows, for each alias row, its name/sku/price/
--   is_enabled and its order + subscription counts. READ IT FIRST. Disabling a row
--   with existing orders is still safe, but a high order count may mean the
--   "duplicate" is the row customers actually purchased from — investigate before
--   COMMIT.
--
-- SAFE AGAINST THE WRONG ROW
--   Each UPDATE is matched on the alias uuid AND the Brello tenant AND requires the
--   alias row's sku to equal the canonical mapped product's sku, so a stale/mistyped
--   uuid disables nothing. Idempotent: a no-op once the row is already disabled.
--
-- 2 duplicate rows in development.

BEGIN;

-- Diagnostic — run this and READ IT before the UPDATEs below take effect.
--   orders / subscriptions: how many rows reference this product. 0 / 0 is the
--   expected shape for a genuine unused duplicate.
SELECT p.id,
       p.name,
       p.sku,
       p.price_cents / 100.0                                        AS price,
       p.is_enabled,
       (SELECT count(*) FROM public.orders o WHERE o.product_id = p.id)        AS orders,
       (SELECT count(*) FROM public.subscriptions s WHERE s.product_id = p.id) AS subscriptions
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
   AND p.id IN (
           '9edac9a0-e2f4-4de1-a5e9-d29c0921906e'::uuid,
           '8ce07cee-7e98-4768-bbb0-0918b00b0da9'::uuid
       )
 ORDER BY p.name;

-- compounded-semaglutide — Compounded Semaglutide (duplicate row)
--   Disable the alias row only when it shares the canonical row's sku (so a
--   mistyped uuid, or one that is NOT actually this product, touches nothing).
UPDATE public.products dup
   SET is_enabled = false,
       updated_at = now()
  FROM public.tenants t,
       public.products canon
 WHERE dup.tenant_id = t.id
   AND t.slug        = 'brello'
   AND dup.id        = '9edac9a0-e2f4-4de1-a5e9-d29c0921906e'::uuid
   AND canon.id      = 'fb802241-1340-405e-b272-1aa46ffd4007'::uuid
   AND canon.tenant_id = dup.tenant_id
   AND dup.sku       = canon.sku
   AND dup.is_enabled IS DISTINCT FROM false;

-- compounded-tirzepatide — Compounded Tirzepatide (duplicate row)
--   Disable the alias row only when it shares the canonical row's sku (so a
--   mistyped uuid, or one that is NOT actually this product, touches nothing).
UPDATE public.products dup
   SET is_enabled = false,
       updated_at = now()
  FROM public.tenants t,
       public.products canon
 WHERE dup.tenant_id = t.id
   AND t.slug        = 'brello'
   AND dup.id        = '8ce07cee-7e98-4768-bbb0-0918b00b0da9'::uuid
   AND canon.id      = '29a10b97-27d9-4847-935e-488b21c8d21a'::uuid
   AND canon.tenant_id = dup.tenant_id
   AND dup.sku       = canon.sku
   AND dup.is_enabled IS DISTINCT FROM false;

-- Confirm the result: every alias row above should now read is_enabled = false,
-- and the canonical row for each slug should remain is_enabled = true.
SELECT p.name, p.sku, p.is_enabled,
       p.id IN ('9edac9a0-e2f4-4de1-a5e9-d29c0921906e'::uuid,
           '8ce07cee-7e98-4768-bbb0-0918b00b0da9'::uuid) AS is_duplicate_row
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
   AND p.sku IN (
     SELECT sku FROM public.products WHERE id IN ('9edac9a0-e2f4-4de1-a5e9-d29c0921906e'::uuid,
           '8ce07cee-7e98-4768-bbb0-0918b00b0da9'::uuid)
   )
 ORDER BY p.sku, is_duplicate_row;

-- Happy? COMMIT. Not happy? ROLLBACK — nothing above has been persisted yet.
COMMIT;
