-- Product "What's Included" bullets → products.included_features
-- Environment: production
--
-- Generated by scripts/generate-product-included-features-sql.mjs. Do not hand-edit: regenerate.
-- Source: brellohealth.com product pages ("What's Included")
--         + products.config.ts (the website-slug → platform-uuid map, per env)
--
-- WHAT THIS WRITES
--   included_features only — the bullet list the patient product page shows near the
--   CTA. A JSONB array of strings (the column is JSONB, default '[]'). The patient UI
--   hides the "What's Included" block when this array is empty, so populating it is
--   what makes the section appear. Also editable in Nexus (the "What's Included" tab).
--
-- WHAT IT DOES NOT WRITE
--   Nothing else — no price, no metadata.pdp content, no other column.
--
-- SAFE TO RE-RUN
--   Idempotent. The UPDATE's "IS DISTINCT FROM" guard means a row already holding the
--   intended array is skipped, so updated_at moves only on a real change.
--
-- SAFE AGAINST THE WRONG ROW
--   Matched on the product uuid AND the Brello tenant (resolved by slug, since the
--   tenant uuid differs per environment), so a stale uuid updates nothing rather than
--   another tenant's row. Every environment's products table also holds other tenants'
--   rows (production carries CareLink-owned compounded-* products); the tenant
--   predicate keeps this Brello-only.
--
-- 10 products in production.

BEGIN;

-- compounded-tirzepatide — Compounded Tirzepatide  (7 bullets)
UPDATE public.products p
   SET included_features = '["Tirzepatide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = 'fedb5a5a-802d-4ca2-ac35-34d663721524'::uuid
   AND p.included_features IS DISTINCT FROM '["Tirzepatide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-semaglutide — Compounded Semaglutide  (7 bullets)
UPDATE public.products p
   SET included_features = '["Semaglutide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '50e94723-5385-432c-bfcb-1b27fbab31d2'::uuid
   AND p.included_features IS DISTINCT FROM '["Semaglutide Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-nad — Compounded NAD+  (7 bullets)
UPDATE public.products p
   SET included_features = '["NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '69294e9f-3146-440f-913b-e261c685ef86'::uuid
   AND p.included_features IS DISTINCT FROM '["NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-sermorelin — Compounded Sermorelin  (7 bullets)
UPDATE public.products p
   SET included_features = '["Sermorelin Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '971f89bb-4916-479b-8b0e-a74821ccff8b'::uuid
   AND p.included_features IS DISTINCT FROM '["Sermorelin Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- compounded-micc — Compounded MICC  (7 bullets)
UPDATE public.products p
   SET included_features = '["MICC Injection (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '34fa5ae7-c32d-435d-9dfb-182994fc3e7b'::uuid
   AND p.included_features IS DISTINCT FROM '["MICC Injection (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- glp-1-and-nad-tirzepatide — Empowered+ Longevity Lifestyle Plan (Tirzepatide)  (8 bullets)
UPDATE public.products p
   SET included_features = '["Tirzepatide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '32ca74d1-e6e1-4371-bf80-aaa36601732c'::uuid
   AND p.included_features IS DISTINCT FROM '["Tirzepatide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- glp-1-and-nad-semaglutide — Empowered+ Longevity Lifestyle Plan (Semaglutide)  (8 bullets)
UPDATE public.products p
   SET included_features = '["Semaglutide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '1fc79cc3-f5bf-480c-8ade-78a323d1d090'::uuid
   AND p.included_features IS DISTINCT FROM '["Semaglutide Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- glp-1-sermorelin-and-nad-tirzepatide — Thrive Forward Longevity Lifestyle Plan (Tirzepatide)  (9 bullets)
UPDATE public.products p
   SET included_features = '["Tirzepatide Medication (If Approved)","Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '5e45b3f1-c637-45b3-af8f-f2f812f6fb26'::uuid
   AND p.included_features IS DISTINCT FROM '["Tirzepatide Medication (If Approved)","Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- glp-1-sermorelin-and-nad-semaglutide — Thrive Forward Longevity Lifestyle Plan (Semaglutide)  (9 bullets)
UPDATE public.products p
   SET included_features = '["Semaglutide Medication (If Approved)","Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '2d69f860-beaa-4694-883e-b07fe181fdb3'::uuid
   AND p.included_features IS DISTINCT FROM '["Semaglutide Medication (If Approved)","Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- sermorelin-and-nad — Midlife Thrive (Sermorelin & NAD+)  (8 bullets)
UPDATE public.products p
   SET included_features = '["Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb,
       updated_at        = now()
  FROM public.tenants t
 WHERE p.tenant_id = t.id
   AND t.slug      = 'brello'
   AND p.id        = '7164aee0-857e-4494-9fad-2686a0c008d8'::uuid
   AND p.included_features IS DISTINCT FROM '["Sermorelin Medication (If Approved)","NAD+ Medication (If Approved)","Syringes with Needles & Injection Instructions","Brello App: Get Support & Track Progress, All In One Place","Brello Rise: Access to Hundreds of Virtual Fitness & Nutrition Classes","Private Facebook Community","Provider Health Review","Fast Shipping"]'::jsonb;

-- Check this BEFORE you COMMIT.
--
--   has_features   should be true for the products listed above.
--   n              the number of bullets on each — the medication line(s) plus the
--                  six shared service bullets.
--   first          a spot-check that the medication line landed (not an empty array).
SELECT p.name,
       jsonb_typeof(p.included_features) = 'array'
         AND jsonb_array_length(p.included_features) > 0                AS has_features,
       jsonb_array_length(COALESCE(p.included_features, '[]'::jsonb))   AS n,
       p.included_features ->> 0                                        AS first
  FROM public.products p
  JOIN public.tenants  t ON t.id = p.tenant_id
 WHERE t.slug = 'brello'
 ORDER BY p.name;

-- Happy? COMMIT. Not happy? ROLLBACK — nothing above has been persisted yet.
COMMIT;
