<?php
/**
 * AH REST API Endpoints
 *
 * This module registers ALL custom REST API endpoints used across the platform.
 * Centralizing REST routes here prevents mixing API logic into checkout, orders,
 * or other modules.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'AH_Rest_Api' ) ) {

class AH_Rest_Api {

    public function __construct() {
        add_action( 'rest_api_init', array( $this, 'register_api_routes' ) );
    }

    /**
     * Register REST API routes used by BH.
     *
     * Endpoints included:
     * - Stripe webhook (/bh/stripe/webhook)
     * - App user tracking (/bh/app/track-user)
     */
    public function register_api_routes() {

        /**
         * STRIPE WEBHOOK
         *
         * URL: /wp-json/bh/stripe/webhook
         */
        register_rest_route( 'bh', '/stripe/webhook', array(
            'methods'             => 'POST',
            'callback'            => array( $this, 'handle_stripe_webhook_events' ),
            'permission_callback' => '__return_true',
        ) );

        /**
         * APP USER TRACKING
         *
         * URL: /wp-json/bh/app/track-user
         * Commented for testing purposes, to reduce problems on the server.
         */
        register_rest_route( 'bh', '/app/track-user', array(
            'methods'             => 'POST',
            'callback'            => array( $this, 'handle_app_user_tracking' ),
            'permission_callback' => '__return_true',
        ) );
    }

    /**
     * Handle Stripe webhook events.
     *
     * @param WP_REST_Request $request
     * @return WP_REST_Response
     */

	public function handle_stripe_webhook_events( $request ) {
        try {
            $body = @file_get_contents('php://input');
            if ( ! $body ) {
                return array( 'success' => false, 'body' => null );
            }

            $event = json_decode( $body );
            if ( ! $event ) {
                return array( 'success' => false, 'body' => $body, 'event' => null );
            }

            $payment_intent  = $event->data->object;
            $events_accepted = array(
                'payment_intent.succeeded',
                'payment_intent.canceled',
                'payment_intent.payment_failed',
            );

            if ( ! in_array( $event->type, $events_accepted, true ) ) {
                return;
            }

            $emoji            = '🔔';
            $is_status_canceled = false;

            switch ( $event->type ) {
                case 'payment_intent.succeeded':
                    $emoji = '✅';
                    break;

                case 'payment_intent.canceled':
                    $emoji = '⚠️';
                    /**
					 * Reason for cancellation of this PaymentIntent, 
					 * either user-provided 
					 * 		(duplicate, fraudulent, requested_by_customer, or abandoned) 
					 * or 
					 * generated by Stripe internally 
					 * 		(failed_invoice, void_invoice, automatic, or expired).
					 * 
					 * Check if is "automatic"
					 */
                    if ( isset( $payment_intent->cancellation_reason ) && $payment_intent->cancellation_reason === 'automatic' ) {
                        $is_status_canceled = true;
                    }
                    break;

                case 'payment_intent.payment_failed':
                    $emoji = '❌';
                    break;
            }

            if ( ! $is_status_canceled ) {
                return array( 'success' => false, 'event' => $event );
            }

            $intent_url = 'https://dashboard.stripe.com' .
                ( strpos( $payment_intent->id, 'pi_test_' ) === 0 ? '/test' : '' ) .
                '/payments/' . $payment_intent->id;

            if ( isset( $payment_intent->metadata->order_id ) ) {
                $order_id = (int) $payment_intent->metadata->order_id;

                /**
                 * Dispatch internal event so Orders module can handle the
                 * cancellation flow and notifications.
                 */
                do_action(
                    'bh_stripe_payment_intent_canceled',
                    $order_id,
                    $payment_intent,
                    $event,
                    $emoji,
                    $intent_url
                );
            }

        } catch ( Exception $e ) {
            if ( function_exists( 'wc_get_logger' ) ) {
                $logger = wc_get_logger();
                $logger->error(
                    'Stripe Webhook Processed: ' . ( isset( $event->type ) ? $event->type : 'unknown' ),
                    array(
                        'order_id'       => isset( $order_id ) ? $order_id : 'none',
                        'payment_intent' => isset( $payment_intent->id ) ? $payment_intent->id : 'none',
                        'message'        => $e->getMessage(),
                    )
                );
            }

            return array(
                'success' => false,
                'error'   => $e->getMessage(),
            );
        }

        return array( 'success' => true );
    }

    /**
     * Handle user tracking events from the mobile app.
     *
     * @param WP_REST_Request $request
     * @return WP_REST_Response
     */
    function handle_app_user_tracking__($request) {
	    $params =	$request->get_params();
	    $email 	=	sanitize_email($params['email']);
	    $action =	sanitize_text_field($params['action']); // 'install' or 'open'
	    if (empty($email) || empty($action)) {
	        return new WP_Error('missing_data', 'Email and action are required', array('status' => 400));
	    }
	    
	    $user = get_user_by('email', $email);
	    if (!$user) {
	        return new WP_Error('user_not_found', 'User not found', array('status' => 404));
	    }
	    
	    $user_id 	=	$user->ID;
		//$today 		=	current_time('mysql');
		$today_date =	date('Y-m-d');
	    switch ($action) {
	        case 'install':
            	update_user_meta($user_id, '_app_installed_date', $today_date);
	            update_user_meta($user_id, '_app_last_opened', $today_date);
	            update_user_meta($user_id, '_uses_app', 'true');
	            //update_user_meta($user_id, '_app_installed_datetime', $today);
	            //update_user_meta($user_id, '_app_last_used', $today);
	            break;
	            
	        case 'open':
	            //update_user_meta($user_id, '_app_last_used', $today);
	            update_user_meta($user_id, '_app_last_opened', $today_date);
	            update_user_meta($user_id, '_uses_app', 'true');
	            break;
	            
	        case 'uninstall':
	            update_user_meta($user_id, '_uses_app', 'false');
	            break;
	    }
	    
	    return rest_ensure_response(array(
	        'success' => true,
	        'user_id' => $user_id,
	        'email' => $email,
	        'action' => $action,
	        'fields_updated' => array(
	            '_uses_app' => get_user_meta($user_id, '_uses_app', true),
	            '_app_installed_date' => get_user_meta($user_id, '_app_installed_date', true),
	            '_app_last_opened' => get_user_meta($user_id, '_app_last_opened', true)
	        )
	    ));
	}
    function handle_app_user_tracking____( $request ) {
        $json    = $request->get_json_params();
        $params  = ! empty( $json ) ? $json : $request->get_params();
        $user_id = intval( $params['user_id'] ?? 0 );
        $action  = sanitize_text_field( $params['action'] ?? '' );

        wc_get_logger()->info(
            sprintf(
                'track-user IN  | ip: %s | user_id: %d | action: %s | body: %s',
                $_SERVER['REMOTE_ADDR'] ?? 'unknown',
                $user_id,
                $action ?: '(empty)',
                $request->get_body()
            ),
            array( 'source' => 'bh-track-user' )
        );

        if ( ! $user_id || empty( $action ) ) {
            $response = new WP_Error( 'missing_data', 'user_id and action are required', array( 'status' => 400 ) );
            wc_get_logger()->info(
                sprintf( 'track-user OUT | status: 400 | reason: missing_data | user_id: %d | action: %s', $user_id, $action ?: '(empty)' ),
                array( 'source' => 'bh-track-user' )
            );
            return $response;
        }

        $user = get_user_by( 'id', $user_id );
        if ( ! $user ) {
            $response = new WP_Error( 'user_not_found', 'User not found', array( 'status' => 404 ) );
            wc_get_logger()->info(
                sprintf( 'track-user OUT | status: 404 | reason: user_not_found | user_id: %d', $user_id ),
                array( 'source' => 'bh-track-user' )
            );
            return $response;
        }

        $today_date = date( 'Y-m-d' );

        switch ( $action ) {
            case 'install':
                update_user_meta( $user_id, '_app_installed_date', $today_date );
                update_user_meta( $user_id, '_app_last_opened', $today_date );
                update_user_meta( $user_id, '_uses_app', 'true' );
                break;
            case 'open':
                update_user_meta( $user_id, '_app_last_opened', $today_date );
                update_user_meta( $user_id, '_uses_app', 'true' );
                break;
            case 'uninstall':
                update_user_meta( $user_id, '_uses_app', 'false' );
                break;
        }

        $response_data = array(
            'success' => true,
            'user_id' => $user_id,
            'action'  => $action,
            'fields_updated' => array(
                '_uses_app'           => get_user_meta( $user_id, '_uses_app', true ),
                '_app_installed_date' => get_user_meta( $user_id, '_app_installed_date', true ),
                '_app_last_opened'    => get_user_meta( $user_id, '_app_last_opened', true ),
            ),
        );

        wc_get_logger()->info(
            sprintf(
                'track-user OUT | status: 200 | user_id: %d | action: %s | fields: %s',
                $user_id,
                $action,
                json_encode( $response_data['fields_updated'] )
            ),
            array( 'source' => 'bh-track-user' )
        );

        return rest_ensure_response( $response_data );
    }

    function handle_app_user_tracking( $request ) {
        $params  = $request->get_params();
        $action  = sanitize_text_field( $params['action'] ?? '' );
        $user_id = ! empty( $params['user_id'] ) ? (int) $params['user_id'] : 0;

        wc_get_logger()->info(
            sprintf( 'track-user IN  | ip: %s | user_id: %d | action: %s | body: %s',
                $_SERVER['REMOTE_ADDR'] ?? '',
                $user_id,
                $action,
                json_encode( $params )
            ),
            array( 'source' => 'bh-track-user' )
        );

        if ( empty( $action ) || empty( $user_id ) ) {
            wc_get_logger()->info(
                sprintf( 'track-user OUT | status: 400 | reason: missing_data | user_id: %d | action: %s', $user_id, $action ?: '(empty)' ),
                array( 'source' => 'bh-track-user' )
            );
            return new WP_Error( 'missing_data', 'user_id and action are required', array( 'status' => 400 ) );
        }

        $today_date  = date( 'Y-m-d' );
        $cache_key   = 'bh_track_user_' . $user_id . '_' . $action . '_' . $today_date;
        $already_ran = wp_cache_get( $cache_key, 'bh-track-user' );

        if ( $already_ran && $action === 'open' ) {
            return rest_ensure_response( array(
                'success'  => true,
                'user_id'  => $user_id,
                'action'   => $action,
                'deduplicated' => true,
            ) );
        }

        $user = get_user_by( 'id', $user_id );
        if ( ! $user ) {
            wc_get_logger()->info(
                sprintf( 'track-user OUT | status: 404 | reason: user_not_found | user_id: %d', $user_id ),
                array( 'source' => 'bh-track-user' )
            );
            return new WP_Error( 'user_not_found', 'User not found', array( 'status' => 404 ) );
        }

        switch ( $action ) {
            case 'install':
                update_user_meta( $user_id, '_app_installed_date', $today_date );
                update_user_meta( $user_id, '_app_last_opened', $today_date );
                update_user_meta( $user_id, '_uses_app', 'true' );
                break;

            case 'open':
                $last_opened = get_user_meta( $user_id, '_app_last_opened', true );
                if ( $last_opened !== $today_date ) {
                    update_user_meta( $user_id, '_app_last_opened', $today_date );
                }
                $uses_app = get_user_meta( $user_id, '_uses_app', true );
                if ( $uses_app !== 'true' ) {
                    update_user_meta( $user_id, '_uses_app', 'true' );
                }
                $seconds_until_midnight = strtotime( 'tomorrow' ) - time();
                wp_cache_set( $cache_key, 1, 'bh-track-user', $seconds_until_midnight );
                break;

            case 'uninstall':
                update_user_meta( $user_id, '_uses_app', 'false' );
                break;
        }

        $fields = array(
            '_uses_app'           => get_user_meta( $user_id, '_uses_app', true ),
            '_app_installed_date' => get_user_meta( $user_id, '_app_installed_date', true ),
            '_app_last_opened'    => get_user_meta( $user_id, '_app_last_opened', true ),
        );

        wc_get_logger()->info(
            sprintf( 'track-user OUT | status: 200 | user_id: %d | action: %s | fields: %s',
                $user_id, $action, json_encode( $fields )
            ),
            array( 'source' => 'bh-track-user' )
        );

        return rest_ensure_response( array(
            'success'        => true,
            'user_id'        => $user_id,
            'action'         => $action,
            'fields_updated' => $fields,
        ) );
    }

}

new AH_Rest_Api();

}
